version: '3.7'
services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: YOUR_USER_NAME
      POSTGRES_PASSWORD: YOUR_PASSWORD
    volumes:
      - DB_VOLUME_NAME:/var/lib/postgresql/data
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: YOUR_EMAIL
      PGADMIN_DEFAULT_PASSWORD: YOUR_PASSWORD
    ports:
      - '5050:80'
    volumes:
      - PG_VOLUME_NAME:/var/lib/pgadmin
volumes:
  DB_VOLUME_NAME:
  PG_VOLUME_NAME:
